version: '3.8'

services:
  rva-bot:
    build: .
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_API=https://api.telegram.org/bot
      - DB_PATH=/data/rva_bot.db
      - LOG_LEVEL=INFO
      - BOT_TIMEOUT=30
      - MAX_RETRIES=3
      - SERVER_PORT=8080
      - SERVER_READ_TIMEOUT=10
      - SERVER_WRITE_TIMEOUT=10
    volumes:
      - bot_data:/data
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  bot_data:
    driver: local
